version: '3'
services:
  api:
    container_name: rails_api_container
    build:
      context: ../rails_hobby
      dockerfile: ./.docker/Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DEV_DATABASE: ${POSTGRES_DEV_DATABASE}
      POSTGRES_TEST_DATABASE: ${POSTGRES_TEST_DATABASE}
      POSTGRES_PRO_DATABASE: ${POSTGRES_PRO_DATABASE}
    # command: sh -c "rm -f tmp/pids/server.pid"
    volumes:
      - .:/workspace
    tty: true
    stdin_open: true
    ports:
      - 3000:3000

  sidekiq:
    build:
      context: ../rails_hobby
      dockerfile: ./.docker/Dockerfile
    command: bundle exec sidekiq
    volumes:
      - .:/workspace
    depends_on:
      - redis

  redis:
    image: redis:7.0-bookworm
    env_file: .env
    command: redis-server --appendonly yes
    ports:
      - 6379:6379

  db:
    container_name: rails_db_container
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - rails-db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_ALLOW_EMPTY_PASSWORD: "yes"
      POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DEV_DATABASE: ${POSTGRES_DEV_DATABASE}

volumes:
  rails-db-volume: